# --- !Ups
CREATE TABLE "films" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "name" varchar not null,
    "genre" varchar not null,
    "rating" long not null,
    "year" long not null
);

# --- !Downs

DROP TABLE IF EXISTS films;