# --- !Ups
CREATE TABLE "films" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "name" varchar not null,
    "genre" varchar not null,
    "rating" long not null,
    "year" long not null
);

INSERT INTO "films" VALUES (1, 'first film', 'action', 3, 2018);

# --- !Downs

DROP TABLE IF EXISTS films;