language: scala
scala:
  - 2.12.6
script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success: 
  - sbt coverageReport coveralls  
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
deploy:
  provider: heroku
  api_key:
    secure: hjB0r6mKEm64SKhJv+s+GRwe98GNkeuxcYgchD5n1TIgMZ0gEkpRtgcpFg3Fhauk5OzZyP1d1goHFvc6+swR1VGBBuagzmlVDSbVg/jSEKdGFWq4c+SCE7k0PsBu0XNbE7H1D5KMOmpI8L8vx6kudoS3F+EDryHsq6VV6O51z13vyvNOBgFshJU+FwY7e+QjGILquXiyJLm2Vr0Bw79naAw4R3jUGZyrQosvV3gPgtIHDXVibiIzpvA5EDLyoIDLZzTDBQJ94kBnlGTz3X4l7IeOwIld8wlXlMqza59i+W7Of2Lb/ImplrVEWBjRO6VKtm+oSdTr0Q/5WcGZV4i1JMF02ZzYkdc2ToZTWkLrSQUnzYzRoLnwe2iarxl8Jmi/LvbnRvD901khx8ii6p8hiMdHjvVMUdyTFmY2RinhW2VFORVL0xzBBUMVNkrCi2ctcIpNXz8bxFyIGf6cj5XyHYIdqDsx4XasO3gBgEgFROPB+OX1x9K3YNINTeipnYRZ3KDzco5c5CuZgVRvlW20M/2Bx9qnGRnLXJShJKG9Gqr09/dLQ+6/rEAfTQCh9FvyRT3MjnLAStjOalc1HmuVW2zpMkqbPl0XkLb6anx9gNhl5mq1gJEhEEQpHk4/raI2ObJZwv06kwbfggsfeJ/gPEAJFh++DqlOCcgg8v4DQpo=
  app: tdd-filmdb