language: scala
scala:
  - 2.12.6
script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success: 
  - sbt coverageReport coveralls  
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
deploy:
  provider: heroku
  api_key:
    secure: A4MzkwlK5E5UtCqSBnNQMNFXsgBmStFGedc2P6w59/iib7DGvLfLzN8jnzNs9yOm6sYmzFwuGsy4F7VGl1zoRITMLm0TJGo9RdjxV57HgkcrlBUKHvB7y5QJ1IlfKfxPpX0XKvZ9fzJ8Wr8O1CrRpLmlATG68widXGrvopFG9hbydFTrwjXwaEIgosvbsOix1kveyivW+LeZoaG55/QxMhGagWpuJkuCluN3DX5KfB7G1NbwRJEW/q9f/Is19dXpr75+v6xRR7zJLBqBCBjYk0RISIm4jfSFPxwbPBz0Hh+oJhlOvLWWHRzIrnj5EIQ327MexHxB3clDo2aWioJyoPv4JJ3y1uub6B1qFhCQOMrURaLLGd1muNDuPbXpQ3YWH5WUFrcGaaF3KcGwGHjvFAHzpKHRIb4KBPnoGcr1mwWWoE4VeNemKNBfGlMq6VWzhw/15OqzlE7wBFmOiI7AdRHeAWuxdzEACSpNZUmJ1WYtLibZsEeUYlXAs+wix8WKSaW7+PQ+F6xmHuaGEZtdvrrf/lFHqHLHzQ/roFB+0o1OjvhO5aiiOzTINEMPbFWsNeiEkrFvrRulw61JsXruo7TIcqBT4HKYfHmQAd61DY/xw3ld+Mfky7SCoe8nJQ+M0jc0cbvuJcAp5VZbHiSVjKpvy/DR4jNMpOhphN6NBK0=
  app: tdd-filmdb-scala
